In [40]:
import pandas as pd
import seaborn as sns
import scipy.stats as st
import matplotlib.pyplot as plt
import statsmodels.api as sm
import sys

In [64]:
Rec2019= pd.read_csv("ReceivingStatsData/2019R.csv")

null_columns=Rec2019.columns[Rec2019.isnull().any()]
Rec2019[null_columns].isnull().sum()

Pos        57
1D         29
Rec/Br    255
dtype: int64

In [65]:
#Rec2019.loc[[39,50,166,167,176,186,241,,'Pos']='WR'
print(Rec2019[Rec2019['Pos'].isnull()].head(30))

      Rk                     Player   Tm  Age  Pos   G  GS  Tgt  Rec  Yds  \
356  357        Tra Carson\CarsTr01  2TM   27  NaN   3   1    4    4   18
371  372    DeAndrew White\WhitDe01  CAR   28  NaN  10   0    9    4   51
373  374         Cody Core\CoreCo00  NYG   25  NaN  16   0    5    3   28
379  380        T.J. Jones\JoneT.00  NYG   27  NaN   3   0    4    3   38
388  389   Russell Shepard\ShepRu00  NYG   29  NaN   3   0    8    3   25
392  393       Jeff Wilson\WilsJe01  SFO   24  NaN  10   0    5    3   34
396  397        Chad Beebe\BeebCh00  MIN   25  NaN   3   0    2    2   70
397  398      Josh Bellamy\BellJo02  NYJ   30  NaN   7   0    3    2   20
399  400        C.J. Board\BoarC.00  JAX   26  NaN   4   0    4    2   31
404  405     Cethan Carter\CartCe00  CIN   24  NaN  15   0    3    2   13
405  406      Robert Davis\DaviRo00  2TM   24  NaN   6   3    5    2   17
406  407      Ashton Dulin\DuliAs00  IND   22  NaN  13   0    2    2   17
407  408       Tyler Ervin\ErviTy00  2TM   26  NaN  10   0    4    2   11
411  412    Cody Hollister\HollCo00  TEN   26  NaN   5   0    2    2   13
414  415   Darius Jennings\JennDa00  TEN   27  NaN   8   0    5    2   17
415  416        T.J. Logan\LogaT.00  TAM   25  NaN  12   0    3    2   13
417  418       Jason Moore\MoorJa02  LAC   24  NaN  10   0    5    2   43
418  419       Isaac Nauta\NautIs00  DET   22  NaN   6   0    3    2   13
419  420     Roosevelt Nix\NixxRo01  PIT   27  NaN   3   0    3    2    4
420  421  Gunner Olszewski\OlszGu00  NWE   23  NaN   8   0    4    2   34
422  423    Troymaine Pope\PopeTr00  LAC   26  NaN  14   0    3    2   14
423  424      Eric Saubert\SaubEr00  CHI   25  NaN   2   0    3    2   21
425  426   Anthony Sherman\SherAn00  KAN   31  NaN  16   0    3    2   22
428  429       Mike Thomas\ThomMi04  LAR   25  NaN  16   0    5    2   14
429  430    Levine Toilolo\ToilLe00  SFO   28  NaN  13   0    2    2   10
430  431    Michael Walker\WalkMi00  JAX   23  NaN   7   0    3    2   15
432  433       Zach Zenner\ZennZa00  3TM   28  NaN   5   0    3    2   19
433  434       Jamal Agnew\AgneJa00  DET   24  NaN  13   0    2    1   -2
434  435    Javorius Allen\AlleJa01  NYG   28  NaN  10   0    2    1    9
439  440    Ventell Bryant\BryaVe00  DAL   23  NaN  12   0    1    1   15

      1D  YBC  YBC/R  YAC  YAC/R  BrkTkl  Rec/Br  Drop  Drop%
356  0.0    4    1.0   14    3.5       0     NaN     0    0.0
371  3.0   23    5.8   28    7.0       0     NaN     0    0.0
373  2.0   25    8.3    3    1.0       0     NaN     0    0.0
379  2.0   15    5.0   23    7.7       0     NaN     0    0.0
388  1.0   12    4.0   13    4.3       0     NaN     1   12.5
392  1.0   13    4.3   21    7.0       0     NaN     1   20.0
396  2.0    4    2.0   66   33.0       1     2.0     0    0.0
397  1.0   10    5.0   10    5.0       0     NaN     1   33.3
399  1.0   25   12.5    6    3.0       0     NaN     0    0.0
404  2.0    8    4.0    5    2.5       0     NaN     0    0.0
405  2.0   15    7.5    2    1.0       0     NaN     0    0.0
406  NaN   -6   -3.0   23   11.5       0     NaN     0    0.0
407  1.0   -1   -0.5   12    6.0       0     NaN     0    0.0
411  NaN   10    5.0    3    1.5       0     NaN     0    0.0
414  2.0    3    1.5   14    7.0       0     NaN     0    0.0
415  1.0    4    2.0    9    4.5       0     NaN     0    0.0
417  2.0   37   18.5    6    3.0       0     NaN     0    0.0
418  1.0    5    2.5    8    4.0       0     NaN     1   33.3
419  NaN   -5   -2.5    9    4.5       0     NaN     0    0.0
420  1.0   18    9.0   16    8.0       0     NaN     0    0.0
422  1.0    3    1.5   11    5.5       0     NaN     1   33.3
423  1.0    3    1.5   18    9.0       0     NaN     1   33.3
425  2.0   -1   -0.5   23   11.5       0     NaN     1   33.3
428  1.0    4    2.0   10    5.0       0     NaN     1   20.0
429  NaN   -3   -1.5   13    6.5       1     2.0     0    0.0
430  1.0    8    4.0    7    3.5       0     NaN     0    0.0
432  2.0    0    0.0   19    9.5       0     NaN     1   33.3
433  0.0   -3   -3.0    1    1.0       0     NaN     0    0.0
434  0.0    5    5.0    4    4.0       0     NaN     0    0.0
439  1.0   15   15.0    0    0.0       0     NaN     0    0.0

In [68]:
#Create list to store players names for cleaning up
split_player = Rec2019["Player"]
#Split out and store the name of the player
players=[i.split("\\")[0] for i in split_player]
#Split out and store first and last names
fname = [i.split(maxsplit = 1)[0] for i in players]
lname = [i.split(maxsplit = 1)[1] for i in players]
#Add first and last name columns
Rec2019["First Name"]=fname
Rec2019["Last Name"]=lname

In [71]:
Rec2019[['Rk','First Name','Last Name','Tm','Pos','G','GS','Tgt','Rec','Yds','1D','YBC','YBC/R','YAC','YAC/R','BrkTkl','Rec/Br','Drop','Drop%']]

Rec2019['Pos'].replace('wr','WR',inplace = True)
Rec2019['Pos'].replace('te','TE',inplace = True)
Rec2019['Pos'].replace(['rb','FB/rb','fb/rb','fb'],'RB',inplace = True)

SyntaxError: invalid syntax (<ipython-input-38-bb9d57a98230>, line 1)

In [74]:
Positions = Rec2019['Pos'].unique()
Positions =['WR', 'RB', 'TE']
Positions

['WR', 'RB', 'TE']

In [75]:

posdfs = {}
for i in Positions:
    a = i
    
    df= Rec2019[Rec2019['Pos']==i]
    posdfs[a]=df

In [76]:
posdfs['WR']

,Rk,Player,Tm,Age,Pos,G,GS,Tgt,Rec,Yds,...,YBC,YBC/R,YAC,YAC/R,BrkTkl,Rec/Br,Drop,Drop%,First Name,Last Name
0,1,Michael Thomas*+\ThomMi05,NOR,26,WR,16,15,185,149,1725,...,1142,7.7,583,3.9,5,29.8,6,3.2,Michael,Thomas*+
2,3,Keenan Allen*\AlleKe00,LAC,27,WR,16,16,149,104,1199,...,825,7.9,374,3.6,4,26.0,7,4.7,Keenan,Allen*
3,4,DeAndre Hopkins*+\HopkDe00,HOU,27,WR,15,15,150,104,1165,...,778,7.5,387,3.7,9,11.6,4,2.7,DeAndre,Hopkins*+
4,5,Julian Edelman\EdelJu00,NWE,33,WR,16,13,153,100,1117,...,797,8.0,320,3.2,4,25.0,13,8.5,Julian,Edelman
5,6,Julio Jones*\JoneJu02,ATL,30,WR,15,15,157,99,1394,...,1030,10.4,364,3.7,7,14.1,4,2.5,Julio,Jones*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,417,Steven Mitchell\MitcSt02,HOU,25,WR,3,1,6,2,37,...,23,11.5,14,7.0,0,NaN,0,0.0,Steven,Mitchell
424,425,Da'Mari Scott\ScotDa02,NYG,24,WR,5,2,3,2,22,...,8,4.0,14,7.0,0,NaN,1,33.3,Da'Mari,Scott
427,428,Cam Sims\SimsCa00,WAS,23,WR,7,1,3,2,27,...,19,9.5,8,4.0,0,NaN,0,0.0,Cam,Sims
441,442,Austin Carr\CarrAu00,NOR,26,WR,6,3,4,1,9,...,5,5.0,4,4.0,0,NaN,1,25.0,Austin,Carr
450,451,Quincy Enunwa\EnunQu00,NYJ,27,WR,1,1,3,1,-4,...,0,0.0,-4,-4.0,0,NaN,0,0.0,Quincy,Enunwa

In [77]:
posdfs['RB']

,Rk,Player,Tm,Age,Pos,G,GS,Tgt,Rec,Yds,...,YBC,YBC/R,YAC,YAC/R,BrkTkl,Rec/Br,Drop,Drop%,First Name,Last Name
1,2,Christian McCaffrey*+\McCaCh01,CAR,23,RB,16,16,142,116,1005,...,-14,-0.1,1019,8.8,14,8.3,7,4.9,Christian,McCaffrey*+
9,10,Austin Ekeler\EkelAu00,LAC,24,RB,16,8,108,92,993,...,53,0.6,940,10.2,15,6.1,1,0.9,Austin,Ekeler
20,21,Alvin Kamara*\KamaAl00,NOR,24,RB,14,9,97,81,533,...,-24,-0.3,557,6.9,10,8.1,5,5.2,Alvin,Kamara*
21,22,Tarik Cohen\CoheTa00,CHI,24,RB,16,11,104,79,456,...,27,0.3,429,5.4,5,15.8,9,8.7,Tarik,Cohen
24,25,Leonard Fournette\FourLe00,JAX,24,RB,15,15,100,76,522,...,-36,-0.5,558,7.3,8,9.5,6,6.0,Leonard,Fournette
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,410,Wes Hills\HillWe00,DET,24,RB,1,1,2,2,1,...,-2,-1.0,3,1.5,0,NaN,0,0.0,Wes,Hills
421,422,Elijhaa Penny\PennEl00,NYG,26,RB,16,1,4,2,9,...,-13,-6.5,22,11.0,0,NaN,0,0.0,Elijhaa,Penny
457,458,Jakob Johnson\JohnJa12,NWE,25,RB,4,3,2,1,5,...,4,4.0,1,1.0,0,NaN,0,0.0,Jakob,Johnson
473,474,Bo Scarbrough\ScarBo01,DET,23,RB,6,5,4,1,5,...,-3,-3.0,8,8.0,0,NaN,0,0.0,Bo,Scarbrough
479,480,Keith Smith\SmitKe03,ATL,27,RB,16,5,3,1,13,...,0,0.0,13,13.0,0,NaN,0,0.0,Keith,Smith

In [78]:
posdfs['TE']

,Rk,Player,Tm,Age,Pos,G,GS,Tgt,Rec,Yds,...,YBC,YBC/R,YAC,YAC/R,BrkTkl,Rec/Br,Drop,Drop%,First Name,Last Name
7,8,Travis Kelce*\KelcTr00,KAN,30,TE,16,16,136,97,1229,...,819,8.4,410,4.2,6,16.2,8,5.9,Travis,Kelce*
11,12,Darren Waller\WallDa01,OAK,27,TE,16,16,117,90,1145,...,575,6.4,570,6.3,8,11.3,5,4.3,Darren,Waller
13,14,Zach Ertz*\ErtzZa00,PHI,29,TE,15,15,135,88,916,...,661,7.5,255,2.9,5,17.6,5,3.7,Zach,Ertz*
16,17,George Kittle*+\KittGe00,SFO,26,TE,14,14,107,85,1053,...,451,5.3,602,7.1,8,10.6,2,1.9,George,Kittle*+
26,27,Austin Hooper*\HoopAu00,ATL,25,TE,13,10,97,75,787,...,452,6.0,335,4.5,5,15.0,1,1.0,Austin,Hooper*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,454,Xavier Grimble\GrimXa00,PIT,27,TE,3,1,3,1,3,...,1,1.0,2,2.0,0,NaN,1,33.3,Xavier,Grimble
461,462,Ben Koyack\KoyaBe00,JAX,26,TE,11,6,3,1,9,...,6,6.0,3,3.0,0,NaN,1,33.3,Ben,Koyack
462,463,Chris Manhertz\ManhCh00,CAR,27,TE,15,6,1,1,11,...,2,2.0,9,9.0,0,NaN,0,0.0,Chris,Manhertz
480,481,Tyrone Swoopes\SwooTy00,SEA,25,TE,5,2,1,1,5,...,-2,-2.0,7,7.0,0,NaN,0,0.0,Tyrone,Swoopes
483,484,Jordan Thomas\ThomJo05,HOU,23,TE,5,2,3,1,8,...,5,5.0,3,3.0,0,NaN,0,0.0,Jordan,Thomas